### PR TITLE
Bug/added by ordering

### PR DESCRIPTION
**Pull request by qoobaa**

### CODE REVIEW

**Comment by agnessa** [comment]
Something is still not quite right I think - as you can see, this list should be ordered by added, but somehow an indicator added by a team is in between system indicators. This does not happen in develop.

screen shot 2017-11-09 at 11 12 30

**Comment by qoobaa** [comment]
screenshot 2017-11-0912 22 36

This is how it works on production…

**Comment by simaob** [comment]
what's the verdict here? =)

**Comment by agnessa** [comment]
not ready yet, need to test this again once https://github.com/Vizzuality/emissions-scenario-portal/pull/157 merged

**Pull request merged**
