### PR TITLE
Updated some model attributes descriptions and names

### PR DESCRIPTION
**Pull request by qoobaa**
I'm not sure about the following lines:

`Technology Choice,"What is the model of technology choice? (logit, linear programming, bottom-up optimization, etc.)"`
`Global Warming Potentials,What global warming potentials (GWP's) are used for different greenhouse gases? Name source (for example IPCC AR4 100-yr GWP's) or specify values.`
`Technology Constraints,What expansion and share constraints were assumed for key technologies (like electrical generation sources)?`
`Trade restrictions,"What trade restrictions were assumed, if any?"`
`Solar power supply,"What are the model assumptions on regional solar power supply? (e.g., Regional supply curves, no limits)"`,
`Wind power supply,"What are the model assumptions on regional wind power supply? (e.g., Regional supply curves, no limits)"`
`Bioenergy,"What are the model assumptions on regional bioenergy supply? (e.g., Regional supply curves, regional production limits, endogenous land competition, no limits)"`
`CO2 storage supplies,"What are the model assumptions on regional supply of CO2 storage opportunities? (e.g., Regional supply curves, not available, no limits)"`

… not sure what they refer to. Maybe I'm updating a wrong file.

### CODE REVIEW

**Comment by simaob** [comment]
It's a few more things, like what I did in the case of scenario's: https://github.com/Vizzuality/emissions-scenario-portal/pull/258

They have changed some fields and removed others. I'm happy to do it if it's not clear to you.

**Comment by qoobaa** [comment]
@simaob check it out.

**Comment by simaob** [comment]
Hey Kuba,
there is still a mismatch between the file they provided (on Basecamp) and the file we get when exporting the models, see screenshot.

screen shot 2018-03-05 at 17 18 07

It seems that there are some attributes that need removing and at least one whose name changed "Maintainer Name" should be now "Maintainer Institute".

And it would be worth re-arranging the yml file, so that the attributes are exported in their groups.

Thanks!

**Comment by qoobaa** [comment]
Should be fixed now.

**Comment by simaob** [comment]
There are still some things that are different:

- We need to remove the "Development year" attribute;
- We need don't need to remove 'Key Usage';
   -> About,Key Usage,What is this model known for? What topical areas/qustions is it especially useful for?,Text (Alphanumeric),,,,,

- We need to add: 
  - Base year: Time,Base Year,What base year was used for the model?,Text (Alphanumeric),,,,,
  - Time Horizon:  Time,Time Horizon,How far does the model run into the future?,Picklist and Text (Alphanumeric),,,,,
  - Time Step: Time,Time Step,What time interval is used for the model output?,Picklist and Text (Alphanumeric),,,,,

- We need to amend:
  - "Population Assumptions" should be just "Population"
  - "GDP Assumptions" should be just "GDP"
  - "Input Data" should be "Other Input Data"

**Pull request merged**
