### PR TITLE
fixed select2

### PR DESCRIPTION
**Pull request by qoobaa**

### CODE REVIEW

**Comment by simaob** [comment]
It seems that this PR is introducing a style issue, with the deselect 'x' not aligning with the text. While using Chrome, see screenshot:

screen shot 2018-01-30 at 12 20 10

**Comment by qoobaa** [comment]
Thanks for checking. It was broken on Firefox before, now it's broken on Chrome. I'll try to make it work on both.

**Comment by qoobaa** [comment]
Should be fixed now.

**Comment by simaob** [comment]
It is =) Thanks

**Pull request merged**
